### ISSUE TITLE
いいアイデア

### ISSUE THREAD

**Issue by hutaband** [c0a2115063/ProjExD#12]
https://github.com/c0a2115063/ProjExD/blob/93160d1ff6a62a96b039dfe52ffbd84ea819d868/ex03/maze.py#L49
　　　！！　　　　　　　　　　　　　　　　　！　！
　！！！！！！！　　　　　　！！！！！！！　！　！　　　　　　　　　！　　　　　　　！
　　　！！　　　　　　　　　　　　　　　　！　　　　　　　　　　　！！　　　　　　　！！
　！！！！　　　　　　　　　　　　　　　　　　　　　　　　　　　　！！　　　　　　　！！
　！！　！　　　　　　　　　　　　　　　　　　　　　　　　　　　　！！　　　　　　　！！
　　！！！　　　　　　　　！　　　　　　　　　　　　　　　　　　　　　！　　　　　　！！
　　　　！　　　　　　　　　！！！！！！！！　　　　　　　　　　　　　　　　　　　！！
　　　！

**Comment by c0a2115063** [comment]
お褒めの言葉ありがとうございます。
