### ISSUE TITLE
爆弾の大きさ

### ISSUE THREAD

**Issue by Daiki-Kobayashi-09067** [c0a2115063/ProjExD#15]
https://github.com/c0a2115063/ProjExD/blob/ba35c6ebea5b1de510f28b66ac2caf939cf4d5e1/ex04/dodge_bomb.py#L48
3つの爆弾の大きさをバラバラにしたらもっとおもしろ味が出ると思った

**Comment by c0a2115063** [comment]
ご意見ありがとうございます。修正してみます！
