### ISSUE TITLE
楽しそう

### ISSUE THREAD

**Issue by c0a21090** [c0a2115063/ProjExD#16]
https://github.com/c0a2115063/ProjExD/blob/ba35c6ebea5b1de510f28b66ac2caf939cf4d5e1/ex04/dodge_bomb.py#L48
爆弾を増やしたことでよりゲーム自体が楽しくなった。
こうかとんのスピードをもっと早くした方が3つの爆弾をよけるのは大変そう

**Comment by c0a2115063** [comment]
少しスピードを下げます。ご意見ありがとう。
