### ISSUE TITLE
good

### ISSUE THREAD

**Issue by c0a21090** [c0a2115063/ProjExD#6]
https://github.com/c0a2115063/ProjExD/blob/4b02621aee80422eb6a34b96faed14fc5a668ec4/ex02/calc.py#L15
計算式の中に×や÷があったら、パイソンでの*や/に置き換えて計算していて自分とは違うやり方でいいと思った。

**Comment by c0a2115063** [comment]
ありがとうございます。TAさんに相談したかいがありました。
