### ISSUE TITLE
色指定方法。

### ISSUE THREAD

**Issue by hutaband** [c0a2115063/ProjExD#8]
https://github.com/c0a2115063/ProjExD/blob/4b02621aee80422eb6a34b96faed14fc5a668ec4/ex02/calc.py#L32
RGBの値をそれぞれ0~255で指定すると様々な色にできる。
random関数を使ってランダムに色を入れたりできる。

**Comment by c0a2115063** [comment]
アドバイスありがとうございます。編集します。

**Comment by c0a2115063** [comment]
編集完了しました！加えて、いらないモジュールを消しました。
