### ISSUE TITLE
色

### ISSUE THREAD

**Issue by Daiki-Kobayashi-09067** [c0a2115063/ProjExD#9]
https://github.com/c0a2115063/ProjExD/blob/4b02621aee80422eb6a34b96faed14fc5a668ec4/ex02/calc.py#L45
数字の色がもっとわかりやすいような背景の色に設定されてればなお良し

**Comment by c0a2115063** [comment]
色の変更で、背景色と文字が被ってしまう事がある為、文字の色は白色にした。
